# Generated by Django 3.0.6 on 2020-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfinAide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_produit',
            name='id_commande_produit',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicoproduce',
            name='id_dico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
