# Generated by Django 3.0.6 on 2020-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfinAide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='desc',
            field=models.CharField(max_length=250),
        ),
    ]
