# Generated by Django 3.0.6 on 2020-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfinAide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
