# Generated by Django 3.0.6 on 2020-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfinAide', '0002_auto_20200514_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nbr_personne',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='commande_produit',
            name='name_produit',
        ),
        migrations.AddField(
            model_name='commande_produit',
            name='name_produit',
            field=models.ManyToManyField(to='ConfinAide.Produit'),
        ),
    ]
